# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided//  萌新不建议精简配置，出现报错还需要加上必要的配置，以下为个人最简配置示例，请确定自己的打卡方式，删掉不需要的即可
{
    "welcome": "用户一，这是一条欢迎语，每次打卡前会打印这句话，用来标记当前打卡用户，如：正在为 *** 打卡......",
    "phone": "123",  // 完美校园登录账号，必填
    "password": "456",  // 完美校园登录密码，必填
    "device_id": "789",  // 已验证完美校园登录设备ID，获取方式为下载蓝奏云链接中的 RegisterDeviceID.zip，必填
    "healthy_checkin": { // 必选一个打卡方式
        "one_check": {  // 第一类健康打卡
            "enable": true  // true 为打开，false 为关闭
        }
    },
    "campus_checkin": {  // 校内打卡，没有就不用管
        "enable": true  // true 为打开，false 为关闭
    },
    "push": {  // 必选一个，单人推送设置，若全部关闭，则使用 push.json 文件的配置，进行统一推送
        "email": {  //  自定义邮箱推送，使用 qq 邮箱推送，就用 qq 邮箱的 smtp 服务地址和端口
            "enable": true,  // true 为打开，false 为关闭
            "smtp_address": "smtp.qq.com",  // stmp服务地址
            "smtp_port": 465,  // stmp服务端口
            "send_email": "***@qq.com",  // 发送邮箱的邮箱地址
            "send_pwd": "****",  // 发送邮箱的邮箱授权码
            "receive_email": "**@qq.com"  // 接收信息的邮箱地址，可自己给自己发
        }
    }
}
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
